In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
import pandas as pd
import plotly.express as pr
import plotly.graph_objects as go

In [6]:
df =pd.read_csv('/content/drive/MyDrive/airline_data.csv')
df

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,...,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
0,1295781,1998,2,4,2,4,1998-04-02,AS,19930,AS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1125375,2013,2,5,13,1,2013-05-13,EV,20366,EV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,118824,1993,3,9,25,6,1993-09-25,UA,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,634825,1994,4,11,12,6,1994-11-12,HP,19991,HP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1888125,2017,3,8,17,4,2017-08-17,UA,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26995,821542,2017,1,1,24,2,2017-01-24,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26996,1910565,2013,2,6,27,4,2013-06-27,B6,20409,B6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26997,9055,2016,3,8,26,5,2016-08-26,AA,19805,AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26998,84136,2009,3,8,8,6,2009-08-08,YV,20378,YV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26999,113029,1993,3,7,17,6,1993-07-17,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df1= df.copy()
df1

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,...,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
0,1295781,1998,2,4,2,4,1998-04-02,AS,19930,AS,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1125375,2013,2,5,13,1,2013-05-13,EV,20366,EV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,118824,1993,3,9,25,6,1993-09-25,UA,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,634825,1994,4,11,12,6,1994-11-12,HP,19991,HP,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1888125,2017,3,8,17,4,2017-08-17,UA,19977,UA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26995,821542,2017,1,1,24,2,2017-01-24,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26996,1910565,2013,2,6,27,4,2013-06-27,B6,20409,B6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26997,9055,2016,3,8,26,5,2016-08-26,AA,19805,AA,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26998,84136,2009,3,8,8,6,2009-08-08,YV,20378,YV,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26999,113029,1993,3,7,17,6,1993-07-17,DL,19790,DL,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.shape

(27000, 110)

In [10]:
df.info

<bound method DataFrame.info of        Unnamed: 0  Year  Quarter  Month  DayofMonth  DayOfWeek  FlightDate  \
0         1295781  1998        2      4           2          4  1998-04-02
1         1125375  2013        2      5          13          1  2013-05-13
2          118824  1993        3      9          25          6  1993-09-25
3          634825  1994        4     11          12          6  1994-11-12
4         1888125  2017        3      8          17          4  2017-08-17
...           ...   ...      ...    ...         ...        ...         ...
26995      821542  2017        1      1          24          2  2017-01-24
26996     1910565  2013        2      6          27          4  2013-06-27
26997        9055  2016        3      8          26          5  2016-08-26
26998       84136  2009        3      8           8          6  2009-08-08
26999      113029  1993        3      7          17          6  1993-07-17

      Reporting_Airline  DOT_ID_Reporting_Airline IATA_CODE_Reporting_Airline  \
0                    AS                     19930                          AS
1                    EV                     20366                          EV
2                    UA                     19977                          UA
3                    HP                     19991                          HP
4                    UA                     19977                          UA
...                 ...                       ...                         ...
26995                DL                     19790                          DL
26996                B6                     20409                          B6
26997                AA                     19805                          AA
26998                YV                     20378                          YV
26999                DL                     19790                          DL

       ... Div4WheelsOff  Div4TailNum  Div5Airport  Div5AirportID  \
0      ...           NaN          NaN          NaN            NaN
1      ...           NaN          NaN          NaN            NaN
2      ...           NaN          NaN          NaN            NaN
3      ...           NaN          NaN          NaN            NaN
4      ...           NaN          NaN          NaN            NaN
...    ...           ...          ...          ...            ...
26995  ...           NaN          NaN          NaN            NaN
26996  ...           NaN          NaN          NaN            NaN
26997  ...           NaN          NaN          NaN            NaN
26998  ...           NaN          NaN          NaN            NaN
26999  ...           NaN          NaN          NaN            NaN

       Div5AirportSeqID Div5WheelsOn Div5TotalGTime Div5LongestGTime  \
0                   NaN          NaN            NaN              NaN
1                   NaN          NaN            NaN              NaN
2                   NaN          NaN            NaN              NaN
3                   NaN          NaN            NaN              NaN
4                   NaN          NaN            NaN              NaN
...                 ...          ...            ...              ...
26995               NaN          NaN            NaN              NaN
26996               NaN          NaN            NaN              NaN
26997               NaN          NaN            NaN              NaN
26998               NaN          NaN            NaN              NaN
26999               NaN          NaN            NaN              NaN

       Div5WheelsOff Div5TailNum
0                NaN         NaN
1                NaN         NaN
2                NaN         NaN
3                NaN         NaN
4                NaN         NaN
...              ...         ...
26995            NaN         NaN
26996            NaN         NaN
26997            NaN         NaN
26998            NaN         NaN
26999            NaN         NaN

[27000 rows x 110 columns]>

In [11]:
df.isna()

,Unnamed: 0,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,Reporting_Airline,DOT_ID_Reporting_Airline,IATA_CODE_Reporting_Airline,...,Div4WheelsOff,Div4TailNum,Div5Airport,Div5AirportID,Div5AirportSeqID,Div5WheelsOn,Div5TotalGTime,Div5LongestGTime,Div5WheelsOff,Div5TailNum
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26995,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
26996,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
26997,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
26998,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
26999,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True

In [12]:
df.isna().sum()

Unnamed: 0              0
Year                    0
Quarter                 0
Month                   0
DayofMonth              0
                    ...
Div5WheelsOn        27000
Div5TotalGTime      27000
Div5LongestGTime    27000
Div5WheelsOff       27000
Div5TailNum         27000
Length: 110, dtype: int64

In [13]:
df.dropna(axis = 1,inplace =True)
df.dtypes

Unnamed: 0            int64
Year                  int64
Quarter               int64
Month                 int64
DayofMonth            int64
                     ...
Div5WheelsOn        float64
Div5TotalGTime      float64
Div5LongestGTime    float64
Div5WheelsOff       float64
Div5TailNum         float64
Length: 110, dtype: object

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27000 entries, 0 to 26999
Columns: 110 entries, Unnamed: 0 to Div5TailNum
dtypes: float64(74), int64(19), object(17)
memory usage: 22.7+ MB

In [20]:
line_data =df.groupby('Month')['ArrDelay'].mean().reset_index()

In [21]:
line_data

    Month  ArrDelay
0       1  7.097321
1       2  6.530025
2       3  5.429533
3       4  4.040055
4       5  5.874889
5       6  9.347515
6       7  8.851436
7       8  7.402630
8       9  2.198975
9      10  3.242506
10     11  4.228961
11     12  9.474149

In [23]:
fig =go.Figure(data = go.Scatter(x=line_data['Month'],y=line_data['ArrDelay'], mode='lines',marker=dict(color='green')))
fig.update_layout(title='Monthly Average Delay of Flights', xaxis_title ='Months', yaxis_title='Delayof Flight Arrival(in minutes)')
fig.show()

In [24]:
fig = pr.pie(df, names='DistanceGroup' , title='Monthly Distance group proportion travelled')
# plt.savefig("123.jpg")
fig.show()

In [26]:
plt.figure(figsize=(8,6), dpi=80)
fig = pr.pie(df, names='DistanceGroup' , title='Monthly Distance group proportion travelled')
plt.savefig("123.png")
fig.show()